import type { CSSProperties } from "react";

export type LocalThemeName = "signal-cobalt" | "arctic-steel" | "linear" | "gamma-dark" | "zine-pop" | "handbook-notes";

export const localThemeStyles: Record<LocalThemeName, CSSProperties> = {
  "signal-cobalt": {
    "--surface-elevated": "#16213b",
    "--surface-code": "#0a1020",
    "--surface-hover": "#1d2b4b",
    "--text-primary": "#e8edf5",
    "--text-secondary": "#93a3bb",
    "--text-muted": "#61708a",
    "--border-subtle": "#223356",
    "--border-strong": "#33507f",
    "--accent-action": "#a3e635",
    "--accent-info": "#38bdf8",
    "--accent-highlight": "#fbbf24",
    "--accent-special": "#c084fc",
    "--shadow-elevation": "0 20px 45px rgba(0, 0, 0, 0.28)",
    "--font-sans": '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    "--font-mono": '"JetBrains Mono", "Fira Code", "Cascadia Code", monospace',
  } as CSSProperties,
  "arctic-steel": {
    "--surface-elevated": "#ffffff",
    "--surface-code": "#eef2f6",
    "--surface-hover": "#e7ecf3",
    "--text-primary": "#162033",
    "--text-secondary": "#4f5f77",
    "--text-muted": "#79869b",
    "--border-subtle": "#d6dde7",
    "--border-strong": "#bbc6d4",
    "--accent-action": "#0f766e",
    "--accent-info": "#0369a1",
    "--accent-highlight": "#b45309",
    "--accent-special": "#7c3aed",
    "--shadow-elevation": "0 18px 30px rgba(15, 23, 42, 0.08)",
    "--font-sans": '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    "--font-mono": '"JetBrains Mono", "Fira Code", "Cascadia Code", monospace',
  } as CSSProperties,
  linear: {
    "--surface-elevated": "#fffdf8",
    "--surface-code": "#f4ede2",
    "--surface-hover": "#f7f1e7",
    "--text-primary": "#2f2417",
    "--text-secondary": "#6c5b4a",
    "--text-muted": "#8c7c68",
    "--border-subtle": "#e4d8c8",
    "--border-strong": "#d0bea8",
    "--accent-action": "#b45309",
    "--accent-info": "#0f766e",
    "--accent-highlight": "#d97706",
    "--accent-special": "#8b5cf6",
    "--shadow-elevation": "0 18px 30px rgba(84, 53, 24, 0.08)",
    "--font-sans": '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    "--font-mono": '"JetBrains Mono", "Fira Code", "Cascadia Code", monospace',
  } as CSSProperties,
  "gamma-dark": {
    "--surface-elevated": "#1a1324",
    "--surface-code": "#0e0a14",
    "--surface-hover": "#231932",
    "--text-primary": "#f4eef9",
    "--text-secondary": "#b3a4c6",
    "--text-muted": "#7a6a8d",
    "--border-subtle": "#2d2141",
    "--border-strong": "#40305d",
    "--accent-action": "#fb7185",
    "--accent-info": "#22d3ee",
    "--accent-highlight": "#facc15",
    "--accent-special": "#c084fc",
    "--shadow-elevation": "0 20px 45px rgba(0, 0, 0, 0.35)",
    "--font-sans": '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    "--font-mono": '"JetBrains Mono", "Fira Code", "Cascadia Code", monospace',
  } as CSSProperties,
  "zine-pop": {
    "--surface-elevated": "#f3ddc9",
    "--surface-code": "#ffee43",
    "--surface-hover": "#17a5ff",
    "--text-primary": "#131313",
    "--text-secondary": "#33261a",
    "--text-muted": "#2b2613",
    "--border-subtle": "#111111",
    "--border-strong": "#111111",
    "--accent-action": "#3d004d",
    "--accent-info": "#1b1f57",
    "--accent-highlight": "#322100",
    "--accent-special": "#2a1248",
    "--shadow-elevation": "0 0 0 2px #111111, 8px 8px 0 rgba(17, 17, 17, 0.88)",
    "--font-sans": '"Space Grotesk", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    "--font-mono": '"Space Mono", "JetBrains Mono", "Fira Code", monospace',
  } as CSSProperties,
  "handbook-notes": {
    "--surface-elevated": "#fffdf8",
    "--surface-code": "#fff1bd",
    "--surface-hover": "#d9e7fb",
    "--text-primary": "#171513",
    "--text-secondary": "#4d4439",
    "--text-muted": "#695d50",
    "--border-subtle": "#1d1b19",
    "--border-strong": "#1d1b19",
    "--accent-action": "#284f8f",
    "--accent-info": "#8b4e1f",
    "--accent-highlight": "#6c5a14",
    "--accent-special": "#7b315d",
    "--shadow-elevation": "0 0 0 1px rgba(29, 27, 25, 0.12), 4px 6px 0 rgba(29, 27, 25, 0.16)",
    "--font-sans": '"IBM Plex Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    "--font-mono": '"IBM Plex Mono", "JetBrains Mono", "Fira Code", monospace',
  } as CSSProperties,
};
